; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-wroom-usbc]
platform = espressif32
board = esp32dev
framework = arduino          ; or espidf — your choice
monitor_speed = 115200
; Optional but very often needed on these cheap boards
; upload_speed = 921600       ; or try 460800 if unstable
upload_speed = 115200
board_build.f_flash = 80000000
board_build.flash_mode = qio   ; or dio — qio is usually faster/safer
board_build.partitions = min_spiffs.csv  ; 1.9 MB app + 190 KB SPIFFS (fits SQLite)

build_flags = -Os   ; optimise for size

lib_deps =
    siara-cc/Sqlite3Esp32
    knolleary/PubSubClient
extra_scripts = pre:load_env.py

; ; ---- Listener mode: MQTT subscriber, waits for "send" signal ---------------
; [env:listener]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 115200
; upload_speed = 921600
; board_build.f_flash = 80000000
; board_build.flash_mode = qio
; lib_deps =
;     siara-cc/Sqlite3Esp32
;     knolleary/PubSubClient
; build_src_filter = +<*> -<main.cpp>
; extra_scripts = pre:load_env.py

; Fixes IntelliSense "cannot open source file" false positives in VSCode
; build_flags =
;   -DCORE_DEBUG_LEVEL=0