; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-wroom-usbc]
platform = espressif32
board = esp32dev
framework = arduino          ; or espidf — your choice
monitor_speed = 115200
; Optional but very often needed on these cheap boards
upload_speed = 921600       ; or try 460800 if unstable
board_build.f_flash = 80000000
board_build.flash_mode = qio   ; or dio — qio is usually faster/safer

lib_deps =
    siara-cc/Sqlite3Esp32

extra_scripts = pre:load_env.py

; Fixes IntelliSense "cannot open source file" false positives in VSCode
; build_flags =
;   -DCORE_DEBUG_LEVEL=0